# Generated by Django 6.0.4 on 2026-04-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='habitaciones/')),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('orden', models.IntegerField(default=0)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='reservas.habitacion')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
