# Generated by Django 6.0.4 on 2026-04-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_imagenhabitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
    ]
